name: Test Documentation
inputs:
  dependencies:
    required: true
    type: string
runs:
  using: "composite"
  steps:
  - name: Obtain Source
    uses: actions/checkout@v2
# #   - if: ${{contains(inputs.dependencies, 'libint')}}
  - name: cache-libint   
    id: cache
    uses: actions/cache@v2
    with:
      path: |
        libint-2.6.0/
        install/
      key: libint-gcc${{ matrix.gcc_version }}
  - name: Generate Javadoc
    env:
      CACHE_LIBINT: ${{steps.cache.outputs.cache-hit}}
    run: |
      export INSTALL_PATH=`pwd`/install
      # check code out
      wget https://github.com/evaleev/libint/releases/download/v2.6.0/libint-2.6.0.tgz
      tar -zxf libint-2.6.0.tgz
      cd libint-2.6.0
      echo "hello " $CACHE_LIBINT >> hello.txt
      # make
      # make install
    shell: bash
