name: Test Documentation
inputs:
  dependencies:
    required: true
    type: string
runs:
  using: "composite"
  steps:
#   - name: Obtain Source
#     uses: actions/checkout@v2
#   - if: ${{contains(inputs.dependencies, 'libint')}}
  - name: cache-libint   
    id: cache
    uses: actions/cache@v2
    with:
      path: |
        libint-2.6.0/
        install/
        build/
      key: libint-gcc${{ matrix.gcc_version }}
    run: |
      echo "go to cache here"  
