name: Handle caches
inputs:
  dependencies:
    required: true
    type: string
outputs:
  cache-libint:
    description: "Cache libint status"
    value: ${{ steps.cacheLibint.outputs.cache-hit }}
  cache-libfort:
    description: "Cache libfort status"
    value: ${{ steps.cacheLibfort.outputs.cache-hit }}
runs:
  using: "composite"
  steps:
  - name: Obtain Source
    uses: actions/checkout@v2
  - if: ${{contains(inputs.dependencies, 'libint')}}
    name: cache-libint   
    id: cacheLibint
    uses: actions/cache@v2
    with:
      path: |
        libint-${{ matrix.libint_version }}/**/
        install/**/
      key: libint-gcc${{ matrix.gcc_version }}
  - if: ${{contains(inputs.dependencies, 'libfort')}}
    name: cache-libfort  
    id: cacheLibfort
    uses: actions/cache@v2
    with:
      path: |
        libfort-${{ matrix.libfort_version }}/**/
        install/**/
      key: cached-libfort