name: Test Documentation
inputs:
  cached-libs:
    required: false
    type: string
  dependencies:
    required: true
    type: string
outputs:
  cache-libint:
    description: "Cache libint status"
    value: ${{ steps.cacheLibint.outputs.cache-hit }}
  cache-tiledarray:
    description: "Cache tiledarray status"
    value: ${{ steps.cacheTiledarray.outputs.cache-hit }}
runs:
  using: "composite"
  steps:
  - name: Obtain Source
    uses: actions/checkout@v2
  - if: ${{contains(inputs.dependencies, 'libint')}}
    name: cache-libint   
    id: cacheLibint
    uses: actions/cache@v2
    with:
      path: |
        libint-2.6.0/**/
        install/**/
      key: libint-gcc${{ matrix.gcc_version }}
  - if: ${{contains(inputs.cached-libs, 'tiledarray')}}
    name: cache-tiledarray   
    id: cacheTiledarray
    uses: actions/cache@v2
    with:
      path: |
        build/_deps/tiledarray-build/**/
        build/_deps/tiledarray-src/**/
        build/_deps/tiledarray-subbuild/**/
        include/tensorwrapper/tensor/backends/tiledarray.hpp
        include/**/
      key: cached-tiledarray
  - name: Generate Javadoc
    env:
      CACHE_LIBINT: ${{steps.cacheLibint.outputs.cache-hit}}
      CACHE_TILEDARRAY: ${{steps.cacheTiledarray.outputs.cache-hit}}
    run: echo "helloworld libint" $CACHE_LIBINT " and tiledarray " $CACHE_TILEDARRAY
    shell: bash
