name: Handle caches
inputs:
  cached-libs:
    required: false
    type: string
  dependencies:
    required: true
    type: string
outputs:
  cache-libint:
    description: "Cache libint status"
    value: ${{ steps.cacheLibint.outputs.cache-hit }}
  cache-libfort:
    description: "Cache libfort status"
    value: ${{ steps.cacheLibfort.outputs.cache-hit }}
runs:
  using: "composite"
  steps:
  - name: Obtain Source
    uses: actions/checkout@v2
  - if: ${{contains(inputs.dependencies, 'libint')}}
    name: cache-libint   
    id: cacheLibint
    uses: actions/cache@v2
    with:
      path: |
        libint-2.6.0/**/
        install/**/
      key: libint-gcc${{ matrix.gcc_version }}
  - if: ${{contains(inputs.cached-libs, 'libfort')}}
    name: cache-libfort  
    id: cacheLibfort
    uses: actions/cache@v2
    with:
      path: |
        libfort-0.4.2/**/
        install/**/
      key: cached-libfort