name: push tmp image to registry
inputs:
  tmp_image_name:
    type: string
    required: true
  tmp_image_tag:
    type: string
    required: true
  image_name:
    type: string
    required: true
  image_tag:
    type: string
    required: true

runs:
  using: "composite"
  steps:
    - name: push image
      run: |
        docker tag ${{inputs.tmp_image_name}}:${{inputs.tmp_image_tag}} ${{inputs.image_name}}:${{inputs.image_tag}}
        docker push ${{inputs.image_name}}:${{inputs.image_tag}}
      shell: bash
