name: Build and Test
inputs:
  CPP_GITHUB_TOKEN:
    required: true

runs:
  using: "composite"
  steps:
    - name: Give Permission
      run: chmod +x ${{github.action_path}}/build_and_test.sh 
      shell: bash 
    - name: Build Documentation
      env:
        # cmake_version: ${{ matrix.cmake_version }}
        # gcc_version: ${{ matrix.gcc_version }}
        # clang_version: ${{ matrix.clang_version }}
        CPP_GITHUB_TOKEN: ${{inputs.CPP_GITHUB_TOKEN}}
      run: ${{github.action_path}}/build_and_test.sh
      shell: bash 