name: Test Documentation
inputs:
  repoName:
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - name: Give Permission
      run: chmod +x ${{github.action_path}}/build_docs.sh 
      shell: bash 
    - name: Build Documentation
      run: ${{github.action_path}}/build_docs.sh ${{inputs.repoName}}
      shell: bash