name: Install package
inputs:
  cmake_version:
    type: string
    required: false
    default: 3.17.0
  gcc_version:
    type: string
    required: false
    default: 9
  clang_version:
    type: string
    required: false
    default: 11
  ubuntu_version:
    type: string
    required: false
    default: 20.04
  madness_version:
    type: string
    required: false
    default: 997e8b458c4234fb6c8c2781a5df59cb14b7e700
  catch2_version:
    type: string
    required: false
    default: 2.13.8
  spdlog_version:
    type: string
    required: false
    default: ad0e89cbfb4d0c1ce4d097e134eb7be67baebb36
  cereal_version:
    type: string
    required: false
    default: 1.3.0
  libfort_version:
    type: string
    required: false
    default: 0.4.2
  libboost_version:
    type: string
    required: false
    default: 1.71.0
  tiledarray_version:
    type: string
    required: false
    default: fab5dc31fc10d88d381e8421d868d2185f164667
  openblas_version:
    type: string
    required: false
    default: 0.3.8
  cblas_version:
    type: string
    required: false
    default: 3.9.0
  lapacke_version:
    type: string
    required: false
    default: 3.9.0
  scalapack_version:
    type: string
    required: false
    default: 2.1.0
  eigen3_version:
    type: string
    required: false
    default: 3.3.7
  openmpi_version:
    type: string
    required: false
    default: 4.0.3
  package_name:
    type: string
    required: required
  parent_image_name:
    type: string
    required: required
  path_to_dockerfile:
    type: string
    required: required

runs:
  using: "composite"
  steps:
    - name: Give Permission
      run: chmod +x ${GITHUB_ACTION_PATH}/image-install_package.sh 
      shell: bash 
    - name: Build Application
      env:
        gcc_version: ${{ inputs.gcc_version }}
        clang_version: ${{ inputs.clang_version }}
        ubuntu_version: ${{ inputs.ubuntu_version }}
        cmake_version: ${{ inputs.cmake_version }}
        madness_version: ${{ inputs.madness_version }}
        catch2_version: ${{ inputs.catch2_version }}
        spdlog_version: ${{ inputs.spdlog_version }}
        cereal_version: ${{ inputs.cereal_version }}
        package_name: ${{ inputs.package_name }}
        parent_image_name: ${{ inputs.parent_image_name }}
        path_to_dockerfile: ${{ inputs.path_to_dockerfile }}
        libfort_version: ${{ inputs.libfort_version }}
        libboost_version: ${{ inputs.libboost_version }}
        tiledarray_version: ${{ inputs.tiledarray_version }}
        openblas_version: ${{ inputs.openblas_version }}
        cblas_version: ${{ inputs.cblas_version }}
        lapacke_version: ${{ inputs.lapacke_version }}
        scalapack_version: ${{ inputs.scalapack_version }}
        eigen3_version: ${{ inputs.eigen3_version }}
        openmpi_version: ${{ inputs.openmpi_version }}
      run: ${GITHUB_ACTION_PATH}/image-install_package.sh
      shell: bash
