name: Install package
inputs:
  cmake_version:
    type: string
    required: false
    default: ''
  gcc_version:
    type: string
    required: false
    default: ''
  clang_version:
    type: string
    required: false
    default: ''
  ubuntu_version:
    type: string
    required: false
    default: ''
  madness_version:
    type: string
    required: false
    default: ''
  catch2_version:
    type: string
    required: false
    default: ''
  spdlog_version:
    type: string
    required: false
    default: ''
  cereal_version:
    type: string
    required: false
    default: ''
  libfort_version:
    type: string
    required: false
    default: ''
  libboost_version:
    type: string
    required: false
    default: ''
  tiledarray_version:
    type: string
    required: false
    default: ''
  openblas_version:
    type: string
    required: false
    default: ''
  cblas_version:
    type: string
    required: false
    default: ''
  lapacke_version:
    type: string
    required: false
    default: ''
  scalapack_version:
    type: string
    required: false
    default: ''
  eigen3_version:
    type: string
    required: false
    default: ''
  openmpi_version:
    type: string
    required: false
    default: ''
  package_name:
    type: string
    required: required
  parent_image_name:
    type: string
    required: required
  path_to_dockerfile:
    type: string
    required: required

runs:
  using: "composite"
  steps:
    - name: Give Permission
      run: chmod +x ${GITHUB_ACTION_PATH}/image-install_package.sh 
      shell: bash 
    - name: Build Application
      env:
        gcc_version: ${{ inputs.gcc_version }}
        clang_version: ${{ inputs.clang_version }}
        ubuntu_version: ${{ inputs.ubuntu_version }}
        cmake_version: ${{ inputs.cmake_version }}
        madness_version: ${{ inputs.madness_version }}
        catch2_version: ${{ inputs.catch2_version }}
        spdlog_version: ${{ inputs.spdlog_version }}
        cereal_version: ${{ inputs.cereal_version }}
        package_name: ${{ inputs.package_name }}
        parent_image_name: ${{ inputs.parent_image_name }}
        path_to_dockerfile: ${{ inputs.path_to_dockerfile }}
        libfort_version: ${{ inputs.libfort_version }}
        libboost_version: ${{ inputs.libboost_version }}
        tiledarray_version: ${{ inputs.tiledarray_version }}
        openblas_version: ${{ inputs.openblas_version }}
        cblas_version: ${{ inputs.cblas_version }}
        lapacke_version: ${{ inputs.lapacke_version }}
        scalapack_version: ${{ inputs.scalapack_version }}
        eigen3_version: ${{ inputs.eigen3_version }}
        openmpi_version: ${{ inputs.openmpi_version }}
      run: ${GITHUB_ACTION_PATH}/image-install_package.sh
      shell: bash
