name: Get dependencies
inputs:
  dependencies:
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - name: Give Permission
      run: chmod +x ${{github.action_path}}/get_dependencies.sh 
      shell: bash 
    - name: Prepare Cache
      id: cache-prepare
      uses: NWChemEx-Project/.github/actions/handle_caches@master
      with:
        cmake_version: ${{ matrix.cmake_version }}
        dependencies: ${{inputs.dependencies}}
        libfort_version: ${{ matrix.libfort_version }}
        libint_version: ${{ matrix.libint_version }}
    - name: Get dependencies
      env:
          CACHE_LIBINT: ${{steps.cache-prepare.outputs.cache-libint}}
          CACHE_LIBFORT: ${{steps.cache-prepare.outputs.cache-libfort}}
      run: ${{github.action_path}}/get_dependencies.sh ${{inputs.dependencies}}
      shell: bash 
