name: Base image gcc clang cmake

on:
  workflow_call:
    inputs:
      cmake_version:
        type: string
        required: true
      gcc_version:
        type: string
        required: true
      clang_version:
        type: string
        required: true
      ubuntu_version:
        type: string
        required: true

jobs:
  image-with-gcc-clang-cmake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: NWChemEx-Project/.github
      - name: Install gcc and clang
        uses: NWChemEx-Project/.github/actions/install_package@master
        with:
          gcc_version: ${{ inputs.gcc_version }}
          clang_version: ${{ inputs.clang_version }}
          ubuntu_version: ${{ inputs.ubuntu_version }}
          package_name: gcc-clang
          parent_image_name: " "
          path_to_dockerfile: .github/Dockerfile/base-gcc-clang.Dockerfile
      - name: Install cmake
        uses: NWChemEx-Project/.github/actions/install_package@master
        with:
          cmake_version: ${{ inputs.cmake_version }}
          package_name: cmake
          parent_image_name: base-gcc-clang
          path_to_dockerfile: .github/Dockerfile/base-cmake.Dockerfile
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CONTAINER_REPO_TOKEN }}
      - name: Push the image
        uses: NWChemEx-Project/.github/actions/push_image@master
        with:
          tmp_image_name: base-cmake
          tmp_image_tag: latest
          image_name: ghcr.io/nwchemex-project/base-cmake
          image_tag: latest
