# Copyright 2023 NWChemEx
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Build nwx_buildenv Image

on: workflow_dispatch

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CONTAINER_REPO_TOKEN }}
      - name: Build Image
        run: |
          cd ./nwx_build_environment
          bash buildenv.sh
        shell: bash
      - name: Push Image
        run: |
          docker tag nwx_buildenv:latest ghcr.io/nwchemex/nwx_buildenv:latest
          docker push ghcr.io/nwchemex/nwx_buildenv:latest
        shell: bash
      