name: C_C++_CI with Docker Image

on:
  workflow_call:
    inputs:
      repo:
        required: true
        type: string
      clang-build:
        required: true
        type: boolean
      gcc-build:
        required: true
        type: boolean
      ninja_build:
        required: true
        type: boolean
      test:
        required: true
        type: boolean
      install:
        required: true
        type: boolean
    secrets:
      CMAIZE_GITHUB_TOKEN:
        required: true
      CONTAINER_REPO_TOKEN:
        required: true

jobs:
  Repo_name_lowcase:
    runs-on: ubuntu-latest
    outputs:
      lowcase_repo_name: ${{ steps.output-repo-name.outputs.repo_name }}
    steps:
    - name: Output repo name in lowcase
      id: output-repo-name
      run: |
        name=${{ inputs.repo }}
        echo "repo_name=${name,,}" >> "$GITHUB_OUTPUT"
  Build:
    runs-on: ubuntu-latest
    needs: Repo_name_lowcase
    container:
      image: ghcr.io/nwchemex-project/build_${{needs.Repo_name_lowcase.outputs.lowcase_repo_name}}:v1
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.CONTAINER_REPO_TOKEN }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Build using Clang
        if: ${{inputs.clang-build == true}}
        env:
          cmake_version: ${{ matrix.cmake_version }}
          clang_version: ${{ matrix.clang_version }}
          ninja_build: ${{ inputs.ninja_build }}
        uses: NWChemEx-Project/.github/actions/image-build@master
        with: 
          CMAIZE_GITHUB_TOKEN: ${{ secrets.CMAIZE_GITHUB_TOKEN }}
          INSTALL: ${{ inputs.install }}
      - name: Build using GCC
        if: ${{inputs.gcc-build == true}}
        env:
          cmake_version: ${{ matrix.cmake_version }}
          gcc_version: ${{ matrix.gcc_version }}
          ninja_build: ${{ inputs.ninja_build }}
        uses: NWChemEx-Project/.github/actions/image-build@master
        with: 
          CMAIZE_GITHUB_TOKEN: ${{ secrets.CMAIZE_GITHUB_TOKEN }}
          INSTALL: ${{ inputs.install }}
      - name: Test Application
        if: ${{inputs.test == true}}
        uses: NWChemEx-Project/.github/actions/image-test@master
        with: 
          CMAIZE_GITHUB_TOKEN: ${{ secrets.CMAIZE_GITHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        if: ${{inputs.gcc-build == true}} && ${{inputs.install == true}}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CONTAINER_REPO_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        if: ${{inputs.gcc-build == true}}  && ${{inputs.install == true}}
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ghcr.io/nwchemex-project/release_${{needs.Repo_name_lowcase.outputs.lowcase_repo_name}}
      - name: Build the image and push
        if: ${{inputs.gcc-build == true}}  && ${{inputs.install == true}}
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
