name: C_C++_CI

on:
  workflow_call:
    inputs:
      dependencies:
        required: true
        type: string
    secrets:
      CPP_GITHUB_TOKEN:
        required: true

jobs:
  build-with-clang:
    uses: NWChemEx-Project/.github/.github/workflows/parallel-build-test.yaml@parallel-template
    with: 
      dependencies: ${{inputs.dependencies}}
      clang-build: true
    secrets:
      CPP_GITHUB_TOKEN: ${{ secrets.CPP_GITHUB_TOKEN }}

  build-with-gcc:
    uses: NWChemEx-Project/.github/.github/workflows/parallel-build-test.yaml@parallel-template
    with: 
      dependencies: ${{inputs.dependencies}}
      clang-build: false
    secrets:
      CPP_GITHUB_TOKEN: ${{ secrets.CPP_GITHUB_TOKEN }}