name: Test Documentation
on:
  workflow_call:
    inputs:
      target:
        type: string
      dependencies:
        required: true
        type: string
      skip_doxygen:
        type: boolean
      
jobs:
  build-documentation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cmake_version: [3.16.3]
    steps:
    - name: Obtain Source
      uses: actions/checkout@v2
    - name: Get dependencies
      env:
        cmake_version: ${{ matrix.cmake_version }}
      uses: NWChemEx-Project/.github/actions/get_dependencies@master
      with:
        dependencies: ${{inputs.dependencies}}
    - name: Build documentation
      env:
        cmake_version: ${{ matrix.cmake_version }}
      uses: NWChemEx-Project/.github/actions/build_docs@master
      with:
        target: ${{inputs.target}}
        skip_doxygen: ${{inputs.skip_doxygen}}